CREATE TABLE `se_accounts` (
  `ACCOUNT_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_audit` (
  `AUDIT_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `EVENT_DATE` datetime NOT NULL,
  `AUDIT_DATE` datetime NOT NULL,
  `EVENT_NAME` varchar(100) NOT NULL,
  `ENTITY_NAME` varchar(100) DEFAULT NULL,
  `ENTITY_ID` varchar(80) DEFAULT NULL,
  `PARENT_ID` varchar(80) DEFAULT NULL,
  `OLD_ENTITY` text,
  `NEW_ENTITY` text,
  `DETAIL` text,
  `CONTEXT` varchar(200) DEFAULT NULL,
  `SESSION_ID` varchar(40) DEFAULT NULL,
  `IP_ADDRESS` varchar(40) DEFAULT NULL,
  `USERAGENT` varchar(400) DEFAULT NULL,
  `SOFT_VERSION_ID` int NOT NULL,
  `SERVER_NAME` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`AUDIT_ID`),
  KEY `se_audit_idx01` (`USER_ID`),
  KEY `se_audit_idx02` (`SOFT_VERSION_ID`),
  CONSTRAINT `se_audit_fk01` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`),
  CONSTRAINT `se_audit_fk02` FOREIGN KEY (`SOFT_VERSION_ID`) REFERENCES `se_soft_versions` (`SOFT_VERSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_email_templates` (
  `EMAIL_TEMPLATE_ID` int NOT NULL,
  `NAME` varchar(40) NOT NULL,
  `TAGS` varchar(200) DEFAULT NULL,
  `SUBJECT` varchar(78) NOT NULL,
  `PLAIN_BODY` text,
  `HTML_BODY` text,
  PRIMARY KEY (`EMAIL_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_errors` (
  `ERROR_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int DEFAULT NULL,
  `ERROR_DATE` datetime NOT NULL,
  `CONTEXT` varchar(200) NOT NULL,
  `CONTEXT_DETAIL` varchar(2000) DEFAULT NULL,
  `EX_CLASS` varchar(200) NOT NULL,
  `EX_MESSAGE` varchar(2000) DEFAULT NULL,
  `EX_STACK_TRACE` text,
  `SOFT_VERSION_ID` int NOT NULL,
  `SERVER_NAME` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ERROR_ID`),
  KEY `se_errors_idx01` (`USER_ID`),
  KEY `se_errors_idx02` (`SOFT_VERSION_ID`),
  CONSTRAINT `se_errors_fk01` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`),
  CONSTRAINT `se_errors_fk02` FOREIGN KEY (`SOFT_VERSION_ID`) REFERENCES `se_soft_versions` (`SOFT_VERSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_notifications` (
  `NOTIFICATION_ID` int NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_TYPE_ID` int NOT NULL,
  `MESSAGE` varchar(4000) NOT NULL,
  `NOTIFICATION_DATE` datetime NOT NULL,
  PRIMARY KEY (`NOTIFICATION_ID`),
  KEY `se_notifications_idx01` (`NOTIFICATION_TYPE_ID`),
  CONSTRAINT `se_notifications_fk01` FOREIGN KEY (`NOTIFICATION_TYPE_ID`) REFERENCES `se_notifications_types` (`NOTIFICATION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_notifications_types` (
  `NOTIFICATION_TYPE_ID` int NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `ICON` varchar(100) NOT NULL,
  `ICON_COLOR` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`NOTIFICATION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_notifications_users` (
  `NOTIFICATION_USER_ID` int NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `READED_DATE` datetime DEFAULT NULL,
  `DELETED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`NOTIFICATION_USER_ID`),
  KEY `se_notifications_users_idx01` (`NOTIFICATION_ID`),
  KEY `se_notifications_users_idx02` (`USER_ID`),
  CONSTRAINT `se_notifications_users_fk01` FOREIGN KEY (`NOTIFICATION_ID`) REFERENCES `se_notifications` (`NOTIFICATION_ID`),
  CONSTRAINT `se_notifications_users_fk02` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_passwords` (
  `PASSWORD_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `DATE_FROM` datetime NOT NULL,
  `DATE_TO` datetime DEFAULT NULL,
  `IS_TEMPORAL` tinyint(1) NOT NULL,
  PRIMARY KEY (`PASSWORD_ID`),
  KEY `se_passwords_idx01` (`USER_ID`),
  CONSTRAINT `se_passwords_fk01` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_passwords_recovery` (
  `PASSWORD_RECOVERY_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `REQUEST_DATE` datetime NOT NULL,
  `EXPIRATION_DATE` datetime NOT NULL,
  `PROCESS_DATE` datetime DEFAULT NULL,
  `VALIDATION_CODE` varchar(32) NOT NULL,
  `IP_ADDRESS` varchar(40) DEFAULT NULL,
  `USERAGENT` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`PASSWORD_RECOVERY_ID`),
  UNIQUE KEY `se_passwords_recovery_uq01` (`VALIDATION_CODE`),
  KEY `se_passwords_recovery_idx01` (`USER_ID`),
  CONSTRAINT `se_passwords_recovery_fk01` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_permissions` (
  `PERMISSION_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NOT NULL,
  `DETAIL` varchar(200) DEFAULT NULL,
  `CATEGORY` varchar(20) DEFAULT NULL,
  `USER_LEVEL` int NOT NULL,
  `IS_USER_DEFINED` tinyint(1) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`PERMISSION_ID`),
  UNIQUE KEY `se_permissions_uq01` (`CATEGORY`,`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

CREATE TABLE `se_properties` (
  `PROPERTY_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NOT NULL,
  `DETAIL` varchar(500) DEFAULT NULL,
  `VALUE` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`PROPERTY_ID`),
  UNIQUE KEY `se_properties_uq01` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_registrations` (
  `REGISTRATION_ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) DEFAULT NULL,
  `LASTNAME` varchar(40) NOT NULL,
  `FIRSTNAME` varchar(40) NOT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `GENDER` enum('M','F') DEFAULT NULL,
  `DOCUMENT_ID` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(200) NOT NULL,
  `CELLPHONE` varchar(40) DEFAULT NULL,
  `VALIDATION_CODE` varchar(32) NOT NULL,
  `FIRST_REGISTRATION_EVENT_ID` int DEFAULT NULL,
  `LAST_REGISTRATION_EVENT_ID` int DEFAULT NULL,
  `USER_ID` int DEFAULT NULL,
  PRIMARY KEY (`REGISTRATION_ID`),
  UNIQUE KEY `se_registrations_uq01` (`VALIDATION_CODE`),
  KEY `se_registrations_idx01` (`FIRST_REGISTRATION_EVENT_ID`),
  KEY `se_registrations_idx02` (`LAST_REGISTRATION_EVENT_ID`),
  KEY `se_registrations_idx03` (`USER_ID`),
  CONSTRAINT `se_registrations_fk01` FOREIGN KEY (`FIRST_REGISTRATION_EVENT_ID`) REFERENCES `se_registrations_events` (`REGISTRATION_EVENT_ID`),
  CONSTRAINT `se_registrations_fk02` FOREIGN KEY (`LAST_REGISTRATION_EVENT_ID`) REFERENCES `se_registrations_events` (`REGISTRATION_EVENT_ID`),
  CONSTRAINT `se_registrations_fk03` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_registrations_events` (
  `REGISTRATION_EVENT_ID` int NOT NULL AUTO_INCREMENT,
  `PREV_REGISTRATION_EVENT_ID` int DEFAULT NULL,
  `REGISTRATION_ID` int NOT NULL,
  `REGISTRATION_STATE_ID` int NOT NULL,
  `EVENT_DATE` datetime NOT NULL,
  `EXPIRATION_DATE` datetime DEFAULT NULL,
  `IP_ADDRESS` varchar(40) DEFAULT NULL,
  `USERAGENT` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`REGISTRATION_EVENT_ID`),
  KEY `se_registrations_events_idx01` (`PREV_REGISTRATION_EVENT_ID`),
  KEY `se_registrations_events_idx02` (`REGISTRATION_ID`),
  KEY `se_registrations_events_idx03` (`REGISTRATION_STATE_ID`),
  CONSTRAINT `se_registrations_events_fk01` FOREIGN KEY (`PREV_REGISTRATION_EVENT_ID`) REFERENCES `se_registrations_events` (`REGISTRATION_EVENT_ID`),
  CONSTRAINT `se_registrations_events_fk02` FOREIGN KEY (`REGISTRATION_ID`) REFERENCES `se_registrations` (`REGISTRATION_ID`),
  CONSTRAINT `se_registrations_events_fk03` FOREIGN KEY (`REGISTRATION_STATE_ID`) REFERENCES `se_registrations_states` (`REGISTRATION_STATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_registrations_states` (
  `REGISTRATION_STATE_ID` int NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `DETAIL` varchar(500) DEFAULT NULL,
  `ICON` varchar(100) DEFAULT NULL,
  `ICON_COLOR` varchar(20) DEFAULT NULL,
  `EXPIRATION_EXPRESSION` varchar(20) DEFAULT NULL,
  `IS_FINAL` tinyint(1) NOT NULL,
  PRIMARY KEY (`REGISTRATION_STATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_roles` (
  `ROLE_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NOT NULL,
  `DETAIL` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `se_roles_permissions` (
  `ROLE_PERMISSION_ID` int NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int NOT NULL,
  `PERMISSION_ID` int NOT NULL,
  `PERMISSION_LEVEL` int NOT NULL,
  PRIMARY KEY (`ROLE_PERMISSION_ID`),
  KEY `se_roles_permissions_idx01` (`ROLE_ID`),
  KEY `se_roles_permissions_idx02` (`PERMISSION_ID`),
  CONSTRAINT `se_roles_permissions_fk01` FOREIGN KEY (`ROLE_ID`) REFERENCES `se_roles` (`ROLE_ID`),
  CONSTRAINT `se_roles_permissions_fk02` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `se_permissions` (`PERMISSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_roles_users` (
  `ROLE_USER_ID` int NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`ROLE_USER_ID`),
  KEY `se_roles_users_idx01` (`ROLE_ID`),
  KEY `se_roles_users_idx02` (`USER_ID`),
  CONSTRAINT `se_roles_users_fk01` FOREIGN KEY (`ROLE_ID`) REFERENCES `se_roles` (`ROLE_ID`),
  CONSTRAINT `se_roles_users_fk02` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_sectors` (
  `SECTOR_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NOT NULL,
  `DETAIL` varchar(200) DEFAULT NULL,
  `SECTOR_PREV` int DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`SECTOR_ID`),
  KEY `se_sectors_idx01` (`SECTOR_PREV`),
  CONSTRAINT `se_sectors_fk01` FOREIGN KEY (`SECTOR_PREV`) REFERENCES `se_sectors` (`SECTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_sectors_users` (
  `SECTOR_USER_ID` int NOT NULL AUTO_INCREMENT,
  `SECTOR_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`SECTOR_USER_ID`),
  KEY `se_sectors_users_idx01` (`SECTOR_ID`),
  KEY `se_sectors_users_idx02` (`USER_ID`),
  CONSTRAINT `se_sectors_users_fk01` FOREIGN KEY (`SECTOR_ID`) REFERENCES `se_sectors` (`SECTOR_ID`),
  CONSTRAINT `se_sectors_users_fk02` FOREIGN KEY (`USER_ID`) REFERENCES `se_users` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_soft_versions` (
  `SOFT_VERSION_ID` int NOT NULL AUTO_INCREMENT,
  `MAJOR` int NOT NULL,
  `MINOR` int NOT NULL,
  `PATCH` int NOT NULL,
  `FASE` varchar(20) NOT NULL,
  `FIRST_STARTUP` datetime NOT NULL,
  `DETAIL` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`SOFT_VERSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `se_users` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` int DEFAULT NULL,
  `USERNAME` varchar(20) NOT NULL,
  `LASTNAME` varchar(40) NOT NULL,
  `FIRSTNAME` varchar(40) NOT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  `CELLPHONE` varchar(40) DEFAULT NULL,
  `MAX_SESSIONS` int NOT NULL,
  `IS_KILL_PREV_SESSION` tinyint(1) NOT NULL,
  `MAX_INACTIVE_INTERVAL` int NOT NULL,
  `USER_LEVEL` int NOT NULL,
  `LAST_LOGIN` datetime DEFAULT NULL,
  `INCORRECT_ATTEMPTS` int NOT NULL,
  `IS_LOCKED` tinyint(1) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `se_users_uq01` (`USERNAME`),
  KEY `se_users_idx01` (`ACCOUNT_ID`),
  CONSTRAINT `se_users_fk01` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `se_accounts` (`ACCOUNT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `se_whitelist` (
  `WHITELIST_ID` int NOT NULL AUTO_INCREMENT,
  `LASTNAME` varchar(40) NOT NULL,
  `FIRSTNAME` varchar(40) NOT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `GENDER` enum('M','F') DEFAULT NULL,
  `DOCUMENT_ID` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(200) NOT NULL,
  `CELLPHONE` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`WHITELIST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
